{% set name = "fastapi-healthcheck" %}
{% set version = "0.2.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastapi_healthcheck-{{ version }}.tar.gz
  sha256: 139080f2b4ad5d3400054b12e53afb43e97db34bc1d4676db956db2302f0bdde

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - pip
    - poetry
  run:
    - python >=3.9,<4.0
    - fastapi

test:
  imports:
    - fastapi_healthcheck
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jtom38/fastapi_healthcheck
  summary: Base package to handle health checks with FastAPI.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marie59
